import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "./provider";

export const metadata: Metadata = {
  title: "CakeWay 🍰",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container">
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
